ALTER TABLE PROFILES DROP KEY CNN_UN_PROFILE_NAME
ALTER TABLE USERS DROP FOREIGN KEY FK_USERS_PROFILE_ID
ALTER TABLE USERS DROP KEY CNN_UN_USER_NAME
ALTER TABLE MENU_OPTIONS DROP FOREIGN KEY FK_MENU_OPTIONS_PARENT_ID
ALTER TABLE CENTER_AREAS DROP FOREIGN KEY FK_CENTER_AREAS_CENTER_ID
ALTER TABLE INTERNALS DROP FOREIGN KEY FK_INTERNALS_USER_ID
ALTER TABLE INTERNALS DROP FOREIGN KEY FK_INTERNALS_INTERNAL_PARTNER_ID
ALTER TABLE INTERNAL_INFORMATION DROP FOREIGN KEY FK_INTERNAL_INFORMATION_PERSON_ID
ALTER TABLE PROFILE_OPTIONS DROP FOREIGN KEY FK_PROFILE_OPTIONS_PROFILE_ID
ALTER TABLE PROFILE_OPTIONS DROP FOREIGN KEY FK_PROFILE_OPTIONS_MENU_ID
ALTER TABLE INTERNAL_ADD_INFO DROP FOREIGN KEY FK_INTERNAL_ADD_INFO_INFORMATION_ID
DROP TABLE PROFILES
DROP TABLE USERS
DROP TABLE MENU_OPTIONS
DROP TABLE CENTERS
DROP TABLE CENTER_AREAS
DROP TABLE INTERNALS
DROP TABLE INTERNAL_INFORMATION
DROP TABLE PROFILE_OPTIONS
DROP TABLE INTERNAL_ADD_INFO
DELETE FROM SEQ_MENU_OPTION_ID WHERE MENU_KEY = 'MENU_ID'
DELETE FROM SEQ_CENTERS_ID WHERE CENTER_KEY = 'CENTER_ID'
DELETE FROM SEQ_PROFILE_ID WHERE PROFILE_KEY = 'PROFILE_ID'
DELETE FROM SEQ_INTERNALS_ID WHERE INTERNAL_KEY = 'INTERNAL_ID'
DELETE FROM SEQ_USER_ID WHERE USER_KEY = 'USER_ID'
DELETE FROM SEQ_CENTER_AREAS_ID WHERE AREA_KEY = 'AREA_ID'
DELETE FROM SEQ_INTERNAL_ADDITIONAL_INFO_ID WHERE INT_ADD_INF_KEY = 'INT_ADD_INF_ID'
